---
version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=user
    ports:
      - "1252:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:

